### ISSUE TITLE
ngx-forms-builder@0.5.3 requires a peer of reflect-metadata@^8.2.2

### ISSUE THREAD

**Issue by EngelaereAntoine** [RaymondCoplin/ngx-forms-builder#3]
Hello,

I think there is an issue here :

https://github.com/RaymondCoplin/ngx-forms-builder/blob/52e8334b2cb767175a357757ee9c3b878a1df9d3/projects/ngx-forms-builder/package.json#L22

the  reflect-metadata@^8.2.2 doesn't exists

I think you should update with this version :

https://github.com/RaymondCoplin/ngx-forms-builder/blob/087d69b12c9aefbbe29057a8a6fde3a70094dd7f/package.json#L26

Thank you

**Comment by RaymondCoplin** [comment]
Thanks, @EngelaereAntoine, the Issue was fixed.
